# l=[1,2,'python','java']
# fs=frozenset(l)
# print(len(fs))
# # print(max(fs))
# # print(min(fs))
# # print(sum(fs))
# print(id(fs))
f=frozenset({2,4,6,8,'python'},)
l=frozenset({20,40,80,'java','python'})
print(f.union(l))
print(f.intersection(l))
print(f.difference(l))
print(f.symmetric_difference(l))
print(f.isdisjoint(l))
print(f.issuperset(l))